services:
  _defaults:
    autowire: false
    autoconfigure: false

  ErgoSarapu\DonationBundle\Controller\AdminDashboardController:
    autoconfigure: true
    autowire: true

  ErgoSarapu\DonationBundle\Controller\Admin\LoginController:
    autoconfigure: true
    autowire: true

  ErgoSarapu\DonationBundle\Controller\Admin\PaymentCrudController:
    autoconfigure: true
    autowire: true

  ErgoSarapu\DonationBundle\Controller\IndexController:
    autoconfigure: true
    calls:
      - ['setContainer', ['@Psr\Container\ContainerInterface']]

  ErgoSarapu\DonationBundle\Controller\PaymentDoneController:
    autoconfigure: true
    calls:
      - ['setContainer', ['@Psr\Container\ContainerInterface']]

  ErgoSarapu\DonationBundle\Twig\Components\DonationForm:
    autoconfigure: true
    calls:
      - ['setContainer', ['@Psr\Container\ContainerInterface']]
