name: Build

on:
  push:
    branches: 
      - master
      - 'feature/**'
  pull_request:
    branches:
      - master

jobs:
  phpunit:
    runs-on: ubuntu-latest

    env:
      SYMFONY_DEPRECATIONS_HELPER: "max[direct]=0"
      DATABASE_URL: "pdo-mysql://db:db@127.0.0.1/db"

    strategy: 
      fail-fast: false
      matrix:
        include:
          - php: 8.2
            symfony: 6.4.*
          - php: 8.3
            symfony: 6.4.*
          - php: 8.2
            symfony: 7.0.*
          - php: 8.3
            symfony: 7.0.*
          - php: 8.2
            symfony: 7.1.*
          - php: 8.3
            symfony: 7.1.*

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
            php-version: ${{ matrix.php }}
            extensions: pdo_sqlite

      - name: Configure Symfony version ${{ matrix.symfony }}
        run: |
            composer global config --no-plugins allow-plugins.symfony/flex true
            composer global require --no-interaction --no-progress symfony/flex:^2.4
            composer config extra.symfony.require "${{ matrix.symfony }}"

      - name: Install dependencies
        run: composer update

      - name: Run Unit Tests
        run: vendor/bin/simple-phpunit --testsuite Unit
      
      - name: Migrate database
        run: |
          mkdir migrations
          # Wait for the MariaDB service to be available
          for i in {1..30}; do
            if nc -z mariadb 3306; then
              echo "MariaDB is up!"
              break
            fi
            echo "Waiting for MariaDB..."
            sleep 1
          done
          ./vendor/bin/doctrine-migrations migrations:diff --no-interaction
          ./vendor/bin/doctrine-migrations migrations:migrate --no-interaction

      - name: Run Functional Tests
        run: |
          ./vendor/bin/simple-phpunit --testsuite Functional

      - name: Run Integration Tests
        run: |
          ./vendor/bin/simple-phpunit --testsuite Integration

    services:
      mariadb:
        image: mariadb:10.5
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: db
          MYSQL_USER: db
          MYSQL_PASSWORD: db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=3