name: Build

on:
  push:
    branches: 
      - master
      - 'feature/**'
  pull_request:
    branches:
      - master

jobs:
  phpunit:
    strategy: 
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        php_version:
          - "8.2"
          - "8.3"
        symfony_version:
          - "6.4"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
            php-version: ${{ matrix.php_version }}
            coverage: none
            extensions: mbstring, intl, pdo, pdo_sqlite, sqlite3
            ini-values: date.timezone=UTC

      - name: symfony/flex is required to install the correct symfony version
        if: ${{ matrix.symfony_version }}
        run: |
            composer global config --no-plugins allow-plugins.symfony/flex true
            composer global require symfony/flex

      - name: Configure Symfony version for symfony/flex
        if: ${{ matrix.symfony_version }}
        run: composer config extra.symfony.require "${{ matrix.symfony_version }}"
        
      - name: Install dependencies
        run: composer update

      - name: Create database
        run: |
          mkdir var && mkdir migrations
          touch var/testdb.sqlite
          ./vendor/bin/doctrine-migrations migrations:diff
          ./vendor/bin/doctrine-migrations migrations:migrate

      - name: Run tests
        env:
          SYMFONY_DEPRECATIONS_HELPER: "disabled"
        run: vendor/bin/simple-phpunit
