name: Build

on:
  push:
    branches: 
      - master
      - 'feature/**'
  pull_request:
    branches:
      - master

jobs:
  phpunit:
    runs-on: ubuntu-latest

    strategy: 
      fail-fast: false
      matrix:
        include:
          - php: 8.2
            symfony: 6.4.*
          - php: 8.3
            symfony: 6.4.*
          - php: 8.2
            symfony: 7.0.*
          - php: 8.3
            symfony: 7.0.*
          - php: 8.2
            symfony: 7.1.*
          - php: 8.3
            symfony: 7.1.*
          - php: 8.2
            symfony: 7.2.*
          - php: 8.3
            symfony: 7.2.*

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
            php-version: ${{ matrix.php }}
            extensions: pdo_sqlite

      - name: Configure Symfony version ${{ matrix.symfony_version }}
        run: |
            composer global config --no-plugins allow-plugins.symfony/flex true
            composer global require --no-interaction --no-progress symfony/flex:^2.2
            composer config extra.symfony.require "${{ matrix.symfony }}"

      - name: Install dependencies
        run: composer update

      - name: Create database
        run: |
          mkdir var && mkdir migrations
          touch var/testdb.sqlite
          ./vendor/bin/doctrine-migrations migrations:diff
          ./vendor/bin/doctrine-migrations migrations:migrate

      - name: Run tests
        env:
          SYMFONY_DEPRECATIONS_HELPER: "disabled"
        run: vendor/bin/simple-phpunit
